WEB_153503_Tatarinov/WEB_153503_Tatarinov/Components/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WEB_153503_Tatarinov.Components;

public class CartViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View();
    }
}

WEB_153503_Tatarinov/WEB_153503_Tatarinov/Controllers/IdentityController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WEB_153503_Tatarinov.Controllers;

public class IdentityController : Controller
{
    public async Task Login()
    {
        await HttpContext.ChallengeAsync(
            "oidc",
            new AuthenticationProperties
            {
                RedirectUri = Url.Action("Index", "Home")
            }
        );
    }

    [HttpPost]
    public async Task Logout()
    {
        await HttpContext.SignOutAsync("cookie");
        await HttpContext.SignOutAsync("oidc",
            new AuthenticationProperties
            {
                RedirectUri= Url.Action("Index", "Home")
            });
    }
}

WEB_153503_Tatarinov/WEB_153503_Tatarinov/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using WEB_153503_Tatarinov.Domain.Entities;
using WEB_153503_Tatarinov.Domain.Models;
using WEB_153503_Tatarinov.Services.CategoryService;
using WEB_153503_Tatarinov.Services.ProductService;
using WEB_153503_Tatarinov.Extensions;

namespace WEB_153503_Tatarinov.Controllers;

public class ProductController : Controller
{
    private readonly IProductService _productService;
    private readonly ICategoryService _categoryService;

    public ProductController(IProductService productService, ICategoryService categoryService)
    {
        _productService = productService;
        _categoryService = categoryService;
    }
    // GET
    public async Task<IActionResult> Index(string? category, int pageNo = 1)
    {
        var categoryResponse = await _categoryService.GetCategoryListAsync();
        if(!categoryResponse.Success)
            return NotFound(categoryResponse.ErrorMessage);
        
        ViewData["categories"] = categoryResponse.Data;
        ViewData["selectedCategory"] = categoryResponse.Data?.SingleOrDefault(c => c.NormalizedName == category);
        
        var productResponse = await _productService.GetProductListAsync(category, pageNo);
        if (!productResponse.Success)
            return NotFound(productResponse.ErrorMessage);

        if (Request.IsAjaxRequest())
        {
            ListModel<Product> data = productResponse.Data!;
            return PartialView("_ProductPartial", new
            {
                data.Items,
                data.CurrentPage,
                data.TotalPages,
                CategoryNormalizedName = category
            });
        }
        else
        {
            return View(productResponse.Data); 
        }
    }
}

WEB_153503_Tatarinov/WEB_153503_Tatarinov/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/lib/fontawesome-free-6.4.2-web/css/all.min.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mx-4">
        <a class="navbar-brand" href="#">15350130</a>
        @await Html.PartialAsync("_MenuPartial")
        @await Html.PartialAsync("_UserInfoPartial")
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        <div class="navbar navbar-dark navbar-expand-md bg-dark">
            <div class="navbar-nav ms-auto">
                <a class="nav-item nav-link" href="http://www.facebook.com">
                    <i class="fa-brands fa-facebook-f fa-2x"></i>
                </a>
                <a class="nav-item nav-link" href="http://www.vk.com">
                    <i class="fa-brands fa-vk fa-2x"></i>
                </a>
                <a class="nav-item nav-link" href="http://www.twitter.com">
                    <i class="fa-brands fa-twitter fa-2x"></i>
                </a>
            </div>
        </div>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WEB_153503_Tatarinov/WEB_153503_Tatarinov/Views/Shared/_MenuPartial.cshtml
@{
    var controller = ViewContext.RouteData.Values["controller"]?.ToString()?.ToLower() ?? String.Empty;
}

<div class="navbar-nav">
    <a asp-controller="Home" asp-action="Index" class="nav-item nav-link @(controller=="home"?"active":"")">Lab_1</a>
    <a asp-controller="Product" asp-action="Index" class="nav-item nav-link @(controller=="product"?"active":"")">Catalog</a>
    @if (User.Identity.IsAuthenticated)
    {
        <a class="nav-item nav-link" asp-area="Admin" asp-page="/Index">Administration</a>
    }
</div>

WEB_153503_Tatarinov/WEB_153503_Tatarinov/Views/Shared/_ProductPartial.cshtml
@{
    var request = ViewContext.HttpContext.Request;
    var returnUrl = request.Path + request.QueryString.ToUriComponent();
}

@foreach (var item in Model.Items)
{
    <div class="col-md-3">
        <div class="card mb-3">
            <img src="@item.ImgPath" class="card-img-top" alt="@item.Name">
            <div class="card-body">
                <h5 class="card-title">@item.Name</h5>
                <p class="card-text">@item.Description</p>
                <a asp-controller="Cart" asp-action="Add" asp-route-id="@item.Id" asp-route-returnurl="@returnUrl"
                   class="btn btn-primary">Add to cart</a>
            </div>
        </div>
    </div>
}
<Pager current-page="@Model.CurrentPage"
       total-pages="@Model.TotalPages"
       category="@(Model.CategoryNormalizedName)">
</Pager>

WEB_153503_Tatarinov/WEB_153503_Tatarinov/Views/Shared/_UserInfoPartial.cshtml
@{
    var userName = User.Claims.FirstOrDefault(
        c => c.Type.Equals("Name", StringComparison.OrdinalIgnoreCase))?.Value;
}


@if (User.Identity.IsAuthenticated)
{
    @await Component.InvokeAsync("Cart")

    <div class="dropdown ms-4 nav-color">
        <button class="btn btn-secondary dropdown-toggle"
                type="button" id="dropdownMenuButton"
                data-bs-toggle="dropdown"
                aria-expanded="false">
            @userName
            <img src="https://localhost:7003/avatar" width="30"
                 alt="@userName" class="rounded nav-color"/>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li>
                <span class="dropdown-item-text">
                    <img src="https://localhost:7003/avatar"
                         width="50" alt="User" class="rounded"/>
                    @userName
                </span>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li>
                <form id="logoutForm" asp-controller="Identity" asp-action="Logout" class="form-inline" method="POST">
                    <button id="logout" type="submit" class="nav-link
                            btn btn-link text-dark">Logout</button>
                </form>
            </li>
        </ul>
    </div>
}
else
{
    <form id="loginForm" class="form-inline" asp-controller="Identity" asp-action="Login">
        <button id="login" type="submit" class="nav-link btn btn-link text-white">
            Login
        </button>
    </form>
}